# Generated by Django 5.1.2 on 2024-12-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_rating_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.ManyToManyField(related_name='movies', to='api.star'),
        ),
    ]
